### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by ccorcos** [jipegit/OSXAuditor#33] opened 2014-09-16 06:25 UTC
An interesting error.

```
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1657, in Main
    ParseQuarantines()
  File "osxauditor.py", line 440, in ParseQuarantines
    JointLSQuarantineEvent += u";" + unicode(Q)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 48: ordinal not in range(128)
```

**Comment by muqiuq** [comment] 2015-10-16 00:05
I got the same error. Is this going to be fixed?

**Comment by jipegit** [comment] 2015-10-31 11:38
Should be fixed.

**Closed** 2015-10-31 11:45 UTC

**Comment by jipegit** [comment] 2015-10-31 11:46
Duplicate of #27
