### ISSUE TITLE
Array index beyond bounds on Safari LastSession

### ISSUE THREAD

**Issue by liquid-sky** [jipegit/OSXAuditor#38] opened 2014-09-22 19:06 UTC
Fails on `LastSession.plist`. Recently updated to Safari 7.1 and Maverick 10.9.5. 

Here's full stack of the error and file contents: 

```
[INFO] /Users/[username]/Library/Safari/LastSession.plist
Traceback (most recent call last):
  File "osxauditor.py", line 1702, in <module>
    Main()
  File "osxauditor.py", line 1663, in Main
    ParseBrowsers()
  File "osxauditor.py", line 808, in ParseBrowsers
    ParseSafari()
  File "osxauditor.py", line 745, in ParseSafari
    ParseSafariProfile(User, UserSafariProfilePath)
  File "osxauditor.py", line 717, in ParseSafariProfile
    LastSession = LastSessionPlist["SessionWindows"][0]["TabStates"][0]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 451, in __getitem__objectAtIndex_
    return container_unwrap(self.objectAtIndex_(idx), RuntimeError)
IndexError: NSRangeException - -[__NSCFArray objectAtIndex:]: index (0) beyond bounds (0)


OSXAuditor ➤ cat  /Users/[username]/Library/Safari/LastSession.plist                                                                                                                               git:master
+/0%
```

**Comment by rdinse** [comment] 2015-03-13 21:41
+1

**Comment by danielcotton** [comment] 2015-06-16 13:50
Pretty sure this is a dupe of #13

**Comment by jipegit** [comment] 2015-10-31 11:20
Can't reproduce it.

**Comment by jipegit** [comment] 2015-10-31 11:44
Duplicate of #28

**Closed by jipegit** 2015-10-31 11:44 UTC
Labels: duplicate
